class Api::V1::Admin::AppTokensController < Api::V1::Admin::BaseAdminController
  before_action :authenticate_admin

  swagger_controller :app_tokens, 'Admin'

  swagger_api :create do
    summary 'Generating new API token'
    notes 'Can be generated by admins only'
    param :header, 'X-APP-Token', :string, :required, 'App Authentication Token'
    param :header, 'X-User-Token', :string, :required, 'Admin Authentication Token'
    response :ok
    response :unauthorized
  end

  def create
    AppToken.destroy_all
    @app_token = AppToken.create(title: 'OnShop')

    render json: { status: 'success', new_token: @app_token.token }
  end
end
